


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;




ALTER SCHEMA "public" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."app_is_admin"() RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$;


ALTER FUNCTION "public"."app_is_admin"() OWNER TO "postgres";


COMMENT ON FUNCTION "public"."app_is_admin"() IS '現在の認証ユーザーが管理者ロールかを判定する安全なヘルパー。';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."activity_logs" (
    "id" bigint NOT NULL,
    "actor_profile_id" "uuid",
    "task_id" "uuid",
    "task_item_id" "uuid",
    "event_type" "text" NOT NULL,
    "details" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."activity_logs" OWNER TO "postgres";


COMMENT ON TABLE "public"."activity_logs" IS '全操作履歴を永続化し、監査・追跡を可能にする。';



ALTER TABLE "public"."activity_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."activity_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."announcement_audience" (
    "announcement_id" "uuid" NOT NULL,
    "profile_id" "uuid" NOT NULL,
    "read_at" timestamp with time zone
);


ALTER TABLE "public"."announcement_audience" OWNER TO "postgres";


COMMENT ON TABLE "public"."announcement_audience" IS 'お知らせの対象ユーザーと既読状態を追跡する。';



CREATE TABLE IF NOT EXISTS "public"."announcements" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text" NOT NULL,
    "body" "text" NOT NULL,
    "scope" "text" NOT NULL,
    "task_id" "uuid",
    "created_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "expires_at" timestamp with time zone,
    CONSTRAINT "announcements_scope_check" CHECK (("scope" = ANY (ARRAY['global'::"text", 'task'::"text"])))
);


ALTER TABLE "public"."announcements" OWNER TO "postgres";


COMMENT ON TABLE "public"."announcements" IS 'ホーム画面向けのお知らせ情報を管理する。';



CREATE TABLE IF NOT EXISTS "public"."locations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "map_id" "uuid" NOT NULL,
    "label" "text" NOT NULL,
    "kind" "text" NOT NULL,
    "coord_x" numeric(5,4) NOT NULL,
    "coord_y" numeric(5,4) NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "locations_coord_x_check" CHECK ((("coord_x" >= (0)::numeric) AND ("coord_x" <= (1)::numeric))),
    CONSTRAINT "locations_coord_y_check" CHECK ((("coord_y" >= (0)::numeric) AND ("coord_y" <= (1)::numeric))),
    CONSTRAINT "locations_kind_check" CHECK (("kind" = ANY (ARRAY['storage'::"text", 'destination'::"text", 'general'::"text"])))
);


ALTER TABLE "public"."locations" OWNER TO "postgres";


COMMENT ON TABLE "public"."locations" IS '設計図上の相対座標と名称を保持し、物品の借用元・移動先を紐づける。';



CREATE TABLE IF NOT EXISTS "public"."maps" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "building" "text" NOT NULL,
    "floor" "text" NOT NULL,
    "image_path" "text" NOT NULL,
    "width_px" integer NOT NULL,
    "height_px" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "maps_height_px_check" CHECK (("height_px" > 0)),
    CONSTRAINT "maps_width_px_check" CHECK (("width_px" > 0))
);


ALTER TABLE "public"."maps" OWNER TO "postgres";


COMMENT ON TABLE "public"."maps" IS '設計図画像のメタデータ（建物・階層）を管理する。';



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "full_name" "text" NOT NULL,
    "role" "text" NOT NULL,
    "phone" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "profiles_role_check" CHECK (("role" = ANY (ARRAY['admin'::"text", 'worker'::"text"])))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


COMMENT ON TABLE "public"."profiles" IS 'Supabase認証ユーザーの拡張情報と役割を保持する。';



COMMENT ON COLUMN "public"."profiles"."role" IS 'アプリ内の権限ロール（admin または worker）。';



CREATE TABLE IF NOT EXISTS "public"."task_item_issues" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "task_item_id" "uuid" NOT NULL,
    "reported_by" "uuid" NOT NULL,
    "status" "text" NOT NULL,
    "category" "text" NOT NULL,
    "description" "text" NOT NULL,
    "resolved_by" "uuid",
    "resolved_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "task_item_issues_category_check" CHECK (("category" = ANY (ARRAY['damage'::"text", 'missing'::"text", 'delay'::"text", 'other'::"text"]))),
    CONSTRAINT "task_item_issues_status_check" CHECK (("status" = ANY (ARRAY['open'::"text", 'investigating'::"text", 'resolved'::"text"])))
);


ALTER TABLE "public"."task_item_issues" OWNER TO "postgres";


COMMENT ON TABLE "public"."task_item_issues" IS '物品に紐づく破損・紛失などの問題報告と対応履歴を記録する。';



CREATE TABLE IF NOT EXISTS "public"."task_item_photos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "task_item_id" "uuid" NOT NULL,
    "url" "text" NOT NULL,
    "caption" "text",
    "captured_at" timestamp with time zone,
    "uploaded_by" "uuid" NOT NULL,
    "kind" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "task_item_photos_kind_check" CHECK (("kind" = ANY (ARRAY['pickup'::"text", 'delivery'::"text", 'issue'::"text"])))
);


ALTER TABLE "public"."task_item_photos" OWNER TO "postgres";


COMMENT ON TABLE "public"."task_item_photos" IS '完了報告や問題報告に紐づく写真証跡を保持する。';



CREATE TABLE IF NOT EXISTS "public"."task_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "task_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "quantity" integer NOT NULL,
    "status" "text" NOT NULL,
    "borrow_location_id" "uuid",
    "destination_location_id" "uuid",
    "assigned_profile_id" "uuid",
    "handler_label" "text",
    "notes" "text",
    "last_status_change_by" "uuid",
    "last_status_changed_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "task_items_quantity_check" CHECK (("quantity" > 0)),
    CONSTRAINT "task_items_status_check" CHECK (("status" = ANY (ARRAY['pending_pickup'::"text", 'in_transit'::"text", 'placed'::"text", 'issue_reported'::"text"])))
);


ALTER TABLE "public"."task_items" OWNER TO "postgres";


COMMENT ON TABLE "public"."task_items" IS '各タスクに紐づく物品とその移動状態を管理する。';



COMMENT ON COLUMN "public"."task_items"."status" IS '物品の現在ステータス（回収待ち/搬送中/設置済み/問題発生）。';



CREATE TABLE IF NOT EXISTS "public"."tasks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "handler_label" "text" NOT NULL,
    "status" "text" NOT NULL,
    "due_at" timestamp with time zone,
    "created_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "tasks_status_check" CHECK (("status" = ANY (ARRAY['not_started'::"text", 'in_progress'::"text", 'blocked'::"text", 'completed'::"text"])))
);


ALTER TABLE "public"."tasks" OWNER TO "postgres";


COMMENT ON TABLE "public"."tasks" IS '物品運搬タスクの基本情報と進捗状態を管理する。';



COMMENT ON COLUMN "public"."tasks"."handler_label" IS '担当者・担当団体を示す自由記述ラベル。';



ALTER TABLE ONLY "public"."activity_logs"
    ADD CONSTRAINT "activity_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."announcement_audience"
    ADD CONSTRAINT "announcement_audience_pkey" PRIMARY KEY ("announcement_id", "profile_id");



ALTER TABLE ONLY "public"."announcements"
    ADD CONSTRAINT "announcements_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."locations"
    ADD CONSTRAINT "locations_map_id_label_key" UNIQUE ("map_id", "label");



ALTER TABLE ONLY "public"."locations"
    ADD CONSTRAINT "locations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."maps"
    ADD CONSTRAINT "maps_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."task_item_issues"
    ADD CONSTRAINT "task_item_issues_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."task_item_photos"
    ADD CONSTRAINT "task_item_photos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."task_items"
    ADD CONSTRAINT "task_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."activity_logs"
    ADD CONSTRAINT "activity_logs_actor_profile_id_fkey" FOREIGN KEY ("actor_profile_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."activity_logs"
    ADD CONSTRAINT "activity_logs_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."activity_logs"
    ADD CONSTRAINT "activity_logs_task_item_id_fkey" FOREIGN KEY ("task_item_id") REFERENCES "public"."task_items"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."announcement_audience"
    ADD CONSTRAINT "announcement_audience_announcement_id_fkey" FOREIGN KEY ("announcement_id") REFERENCES "public"."announcements"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."announcement_audience"
    ADD CONSTRAINT "announcement_audience_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."announcements"
    ADD CONSTRAINT "announcements_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."announcements"
    ADD CONSTRAINT "announcements_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."locations"
    ADD CONSTRAINT "locations_map_id_fkey" FOREIGN KEY ("map_id") REFERENCES "public"."maps"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."task_item_issues"
    ADD CONSTRAINT "task_item_issues_reported_by_fkey" FOREIGN KEY ("reported_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."task_item_issues"
    ADD CONSTRAINT "task_item_issues_resolved_by_fkey" FOREIGN KEY ("resolved_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."task_item_issues"
    ADD CONSTRAINT "task_item_issues_task_item_id_fkey" FOREIGN KEY ("task_item_id") REFERENCES "public"."task_items"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."task_item_photos"
    ADD CONSTRAINT "task_item_photos_task_item_id_fkey" FOREIGN KEY ("task_item_id") REFERENCES "public"."task_items"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."task_item_photos"
    ADD CONSTRAINT "task_item_photos_uploaded_by_fkey" FOREIGN KEY ("uploaded_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."task_items"
    ADD CONSTRAINT "task_items_assigned_profile_id_fkey" FOREIGN KEY ("assigned_profile_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."task_items"
    ADD CONSTRAINT "task_items_borrow_location_id_fkey" FOREIGN KEY ("borrow_location_id") REFERENCES "public"."locations"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."task_items"
    ADD CONSTRAINT "task_items_destination_location_id_fkey" FOREIGN KEY ("destination_location_id") REFERENCES "public"."locations"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."task_items"
    ADD CONSTRAINT "task_items_last_status_change_by_fkey" FOREIGN KEY ("last_status_change_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."task_items"
    ADD CONSTRAINT "task_items_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT ALL ON SCHEMA "public" TO "anon";
GRANT ALL ON SCHEMA "public" TO "authenticated";
GRANT ALL ON SCHEMA "public" TO "service_role";







































































































































































































RESET ALL;

